name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all-targets
      - run: cargo test
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
